"""Add supplier_id to user table"""

revision = '06f5f9908d45'
down_revision = '202510100006'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'contact_email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Contact email address',
               existing_nullable=True)
    op.alter_column('customer', 'contact_phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('customer', 'customer_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Internal customer code (BMS: canag_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'public_customer_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Public code shown on invoices (BMS: ncocg)',
               existing_nullable=True)
    op.alter_column('customer', 'business_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Full business/trade name (BMS: traso)',
               existing_nullable=True)
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='First name for individuals (BMS: rnome)',
               existing_nullable=True)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Last name for individuals (BMS: rcogn)',
               existing_nullable=True)
    op.alter_column('customer', 'fiscal_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Italian tax code - codice fiscale (BMS: cfisc)',
               existing_nullable=True)
    op.alter_column('customer', 'vat_number',
               existing_type=sa.VARCHAR(length=11),
               comment=None,
               existing_comment='Italian VAT number - P.IVA (BMS: cpiva)',
               existing_nullable=True)
    op.alter_column('customer', 'registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Initial registration date (BMS: ianag_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Credit limit amount (BMS: asogl_xivas)',
               existing_nullable=True)
    op.alter_column('customer', 'customer_category',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Customer category/classification (BMS: ccate_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'activity_category',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Activity/industry sector (BMS: ccate_satti)',
               existing_nullable=True)
    op.alter_column('customer', 'gender',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='Gender M/F/O (BMS: csess)',
               existing_nullable=True)
    op.alter_column('customer', 'business_start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Business activity start date (BMS: dinse_ianag)',
               existing_nullable=True)
    op.alter_column('customer', 'financial_status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Financial status code (BMS: cstat_dfiac)',
               existing_nullable=True)
    op.alter_column('customer', 'cash_payment',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Cash payment preference (BMS: bcafl)',
               existing_nullable=True)
    op.alter_column('customer', 'auto_packaging',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Auto packaging flag (BMS: bragg_ximba)',
               existing_nullable=True)
    op.alter_column('customer', 'customer_group',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Customer group name (BMS: tclie_ngrup)',
               existing_nullable=True)
    op.drop_index(op.f('idx_customer_contact_email'), table_name='customer')
    op.drop_index(op.f('idx_customer_customer_code'), table_name='customer')
    op.drop_index(op.f('idx_customer_fiscal_code'), table_name='customer')
    op.drop_index(op.f('idx_customer_public_code'), table_name='customer')
    op.drop_index(op.f('idx_customer_vat_number'), table_name='customer')
    op.alter_column('customer_address', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to customer table',
               existing_nullable=False)
    op.alter_column('customer_address', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Address type (billing, shipping, etc)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this is the default address',
               existing_nullable=True)
    op.alter_column('customer_address', 'address_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Internal address code (BMS: cindi_dclie)',
               existing_nullable=True)
    op.alter_column('customer_address', 'public_address_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Public code shown on documents (BMS: ncocg_dcntr)',
               existing_nullable=True)
    op.alter_column('customer_address', 'province',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='Province code 2 chars (BMS: cprov)',
               existing_nullable=True)
    op.alter_column('customer_address', 'municipality',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Municipality/comune (BMS: rcomu)',
               existing_nullable=True)
    op.alter_column('customer_address', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Main phone number (BMS: cntel)',
               existing_nullable=True)
    op.alter_column('customer_address', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Email address (BMS: tinte_semai)',
               existing_nullable=True)
    op.alter_column('customer_address', 'pricelist_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Price list type (BMS: ctipo_dlist)',
               existing_nullable=True)
    op.alter_column('customer_address', 'payment_terms_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Payment terms code (BMS: cmpag)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_billing_address',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Billing address flag (BMS: busat_xfatt)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_shipping_address',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Shipping address flag (BMS: busat_xinme)',
               existing_nullable=True)
    op.alter_column('customer_address', 'street_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Street name separated (BMS: rviaa_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'street_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Street number (BMS: cnciv_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'internal_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Internal/apartment number (BMS: cnint_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'region',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Region code (BMS: cregi)',
               existing_nullable=True)
    op.alter_column('customer_address', 'zone_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Geographic zone (BMS: czona)',
               existing_nullable=True)
    op.alter_column('customer_address', 'mobile_phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Mobile/additional phone (BMS: cntel_sagg1)',
               existing_nullable=True)
    op.alter_column('customer_address', 'fax',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Fax number (BMS: cntel_sfaxx)',
               existing_nullable=True)
    op.alter_column('customer_address', 'website',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Website URL (BMS: tinte_ssito)',
               existing_nullable=True)
    op.alter_column('customer_address', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment=None,
               existing_comment='GPS latitude (BMS: qcoox)',
               existing_nullable=True)
    op.alter_column('customer_address', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment=None,
               existing_comment='GPS longitude (BMS: qcooy)',
               existing_nullable=True)
    op.alter_column('customer_address', 'promo_pricelist_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Promotional pricelist (BMS: clist_sprom)',
               existing_nullable=True)
    op.alter_column('customer_address', 'shipping_terms',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Shipping/port terms (BMS: cport)',
               existing_nullable=True)
    op.alter_column('customer_address', 'transport_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Transport type (BMS: ctras)',
               existing_nullable=True)
    op.alter_column('customer_address', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Language code (BMS: cling)',
               existing_nullable=True)
    op.alter_column('customer_address', 'currency_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Currency code (BMS: cvalu)',
               existing_nullable=True)
    op.alter_column('customer_address', 'carrier_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Carrier/shipper code (BMS: canag_svett)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_payment_address',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Payment address flag (BMS: busat_xpaga)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_delivery_address',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Delivery address flag (BMS: busat_xsdlg)',
               existing_nullable=True)
    op.alter_column('customer_address', 'registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Address registration date (BMS: iindi_dclie)',
               existing_nullable=True)
    op.alter_column('customer_address', 'iban',
               existing_type=sa.VARCHAR(length=34),
               comment=None,
               existing_comment='IBAN code (BMS: cabix)',
               existing_nullable=True)
    op.alter_column('customer_address', 'bic_swift',
               existing_type=sa.VARCHAR(length=11),
               comment=None,
               existing_comment='BIC/SWIFT code (BMS: ccabx)',
               existing_nullable=True)
    op.alter_column('customer_address', 'discount_1',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               comment=None,
               existing_comment='Discount percentage 1 (BMS: pscon_orica_1)',
               existing_nullable=True)
    op.alter_column('customer_address', 'discount_2',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               comment=None,
               existing_comment='Discount percentage 2 (BMS: pscon_orica_2)',
               existing_nullable=True)
    op.alter_column('customer_address', 'agent_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Sales agent code (BMS: canag_sagen)',
               existing_nullable=True)
    op.alter_column('customer_address', 'sales_point_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Sales point code (BMS: cpven)',
               existing_nullable=True)
    op.alter_column('customer_address', 'vat_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='VAT exemption code (BMS: caiva)',
               existing_nullable=True)
    op.alter_column('customer_address', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Credit limit for this address (BMS: afido_dclie)',
               existing_nullable=True)
    op.drop_index(op.f('idx_address_address_code'), table_name='customer_address')
    op.drop_index(op.f('idx_address_email'), table_name='customer_address')
    op.drop_index(op.f('idx_address_phone'), table_name='customer_address')
    op.drop_index(op.f('idx_address_public_code'), table_name='customer_address')
    op.drop_index(op.f('idx_address_type'), table_name='customer_address')
    op.drop_index(op.f('idx_customer_address_customer_id'), table_name='customer_address')
    op.create_index(op.f('ix_customer_address_customer_id'), 'customer_address', ['customer_id'], unique=False)
    op.add_column('user', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_user_supplier_id_supplier'), 'user', 'supplier', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_supplier_id_supplier'), 'user', type_='foreignkey')
    op.drop_column('user', 'supplier_id')
    op.drop_index(op.f('ix_customer_address_customer_id'), table_name='customer_address')
    op.create_index(op.f('idx_customer_address_customer_id'), 'customer_address', ['customer_id'], unique=False)
    op.create_index(op.f('idx_address_type'), 'customer_address', ['type'], unique=False)
    op.create_index(op.f('idx_address_public_code'), 'customer_address', ['public_address_code'], unique=False)
    op.create_index(op.f('idx_address_phone'), 'customer_address', ['phone'], unique=False)
    op.create_index(op.f('idx_address_email'), 'customer_address', ['email'], unique=False)
    op.create_index(op.f('idx_address_address_code'), 'customer_address', ['address_code'], unique=False)
    op.alter_column('customer_address', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Credit limit for this address (BMS: afido_dclie)',
               existing_nullable=True)
    op.alter_column('customer_address', 'vat_code',
               existing_type=sa.VARCHAR(),
               comment='VAT exemption code (BMS: caiva)',
               existing_nullable=True)
    op.alter_column('customer_address', 'sales_point_code',
               existing_type=sa.VARCHAR(),
               comment='Sales point code (BMS: cpven)',
               existing_nullable=True)
    op.alter_column('customer_address', 'agent_code',
               existing_type=sa.VARCHAR(),
               comment='Sales agent code (BMS: canag_sagen)',
               existing_nullable=True)
    op.alter_column('customer_address', 'discount_2',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               comment='Discount percentage 2 (BMS: pscon_orica_2)',
               existing_nullable=True)
    op.alter_column('customer_address', 'discount_1',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               comment='Discount percentage 1 (BMS: pscon_orica_1)',
               existing_nullable=True)
    op.alter_column('customer_address', 'bic_swift',
               existing_type=sa.VARCHAR(length=11),
               comment='BIC/SWIFT code (BMS: ccabx)',
               existing_nullable=True)
    op.alter_column('customer_address', 'iban',
               existing_type=sa.VARCHAR(length=34),
               comment='IBAN code (BMS: cabix)',
               existing_nullable=True)
    op.alter_column('customer_address', 'registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Address registration date (BMS: iindi_dclie)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_delivery_address',
               existing_type=sa.BOOLEAN(),
               comment='Delivery address flag (BMS: busat_xsdlg)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_payment_address',
               existing_type=sa.BOOLEAN(),
               comment='Payment address flag (BMS: busat_xpaga)',
               existing_nullable=True)
    op.alter_column('customer_address', 'carrier_code',
               existing_type=sa.VARCHAR(),
               comment='Carrier/shipper code (BMS: canag_svett)',
               existing_nullable=True)
    op.alter_column('customer_address', 'currency_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Currency code (BMS: cvalu)',
               existing_nullable=True)
    op.alter_column('customer_address', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Language code (BMS: cling)',
               existing_nullable=True)
    op.alter_column('customer_address', 'transport_type',
               existing_type=sa.VARCHAR(),
               comment='Transport type (BMS: ctras)',
               existing_nullable=True)
    op.alter_column('customer_address', 'shipping_terms',
               existing_type=sa.VARCHAR(),
               comment='Shipping/port terms (BMS: cport)',
               existing_nullable=True)
    op.alter_column('customer_address', 'promo_pricelist_code',
               existing_type=sa.VARCHAR(),
               comment='Promotional pricelist (BMS: clist_sprom)',
               existing_nullable=True)
    op.alter_column('customer_address', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment='GPS longitude (BMS: qcooy)',
               existing_nullable=True)
    op.alter_column('customer_address', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment='GPS latitude (BMS: qcoox)',
               existing_nullable=True)
    op.alter_column('customer_address', 'website',
               existing_type=sa.VARCHAR(),
               comment='Website URL (BMS: tinte_ssito)',
               existing_nullable=True)
    op.alter_column('customer_address', 'fax',
               existing_type=sa.VARCHAR(),
               comment='Fax number (BMS: cntel_sfaxx)',
               existing_nullable=True)
    op.alter_column('customer_address', 'mobile_phone',
               existing_type=sa.VARCHAR(),
               comment='Mobile/additional phone (BMS: cntel_sagg1)',
               existing_nullable=True)
    op.alter_column('customer_address', 'zone_code',
               existing_type=sa.VARCHAR(),
               comment='Geographic zone (BMS: czona)',
               existing_nullable=True)
    op.alter_column('customer_address', 'region',
               existing_type=sa.VARCHAR(),
               comment='Region code (BMS: cregi)',
               existing_nullable=True)
    op.alter_column('customer_address', 'internal_number',
               existing_type=sa.VARCHAR(),
               comment='Internal/apartment number (BMS: cnint_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'street_number',
               existing_type=sa.VARCHAR(),
               comment='Street number (BMS: cnciv_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'street_name',
               existing_type=sa.VARCHAR(),
               comment='Street name separated (BMS: rviaa_dstra)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_shipping_address',
               existing_type=sa.BOOLEAN(),
               comment='Shipping address flag (BMS: busat_xinme)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_billing_address',
               existing_type=sa.BOOLEAN(),
               comment='Billing address flag (BMS: busat_xfatt)',
               existing_nullable=True)
    op.alter_column('customer_address', 'payment_terms_code',
               existing_type=sa.VARCHAR(),
               comment='Payment terms code (BMS: cmpag)',
               existing_nullable=True)
    op.alter_column('customer_address', 'pricelist_type',
               existing_type=sa.VARCHAR(),
               comment='Price list type (BMS: ctipo_dlist)',
               existing_nullable=True)
    op.alter_column('customer_address', 'email',
               existing_type=sa.VARCHAR(),
               comment='Email address (BMS: tinte_semai)',
               existing_nullable=True)
    op.alter_column('customer_address', 'phone',
               existing_type=sa.VARCHAR(),
               comment='Main phone number (BMS: cntel)',
               existing_nullable=True)
    op.alter_column('customer_address', 'municipality',
               existing_type=sa.VARCHAR(),
               comment='Municipality/comune (BMS: rcomu)',
               existing_nullable=True)
    op.alter_column('customer_address', 'province',
               existing_type=sa.VARCHAR(length=2),
               comment='Province code 2 chars (BMS: cprov)',
               existing_nullable=True)
    op.alter_column('customer_address', 'public_address_code',
               existing_type=sa.VARCHAR(),
               comment='Public code shown on documents (BMS: ncocg_dcntr)',
               existing_nullable=True)
    op.alter_column('customer_address', 'address_code',
               existing_type=sa.VARCHAR(),
               comment='Internal address code (BMS: cindi_dclie)',
               existing_nullable=True)
    op.alter_column('customer_address', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='Whether this is the default address',
               existing_nullable=True)
    op.alter_column('customer_address', 'type',
               existing_type=sa.VARCHAR(),
               comment='Address type (billing, shipping, etc)',
               existing_nullable=True)
    op.alter_column('customer_address', 'customer_id',
               existing_type=sa.UUID(),
               comment='Foreign key to customer table',
               existing_nullable=False)
    op.create_index(op.f('idx_customer_vat_number'), 'customer', ['vat_number'], unique=False)
    op.create_index(op.f('idx_customer_public_code'), 'customer', ['public_customer_code'], unique=False)
    op.create_index(op.f('idx_customer_fiscal_code'), 'customer', ['fiscal_code'], unique=False)
    op.create_index(op.f('idx_customer_customer_code'), 'customer', ['customer_code'], unique=False)
    op.create_index(op.f('idx_customer_contact_email'), 'customer', ['contact_email'], unique=False)
    op.alter_column('customer', 'customer_group',
               existing_type=sa.VARCHAR(),
               comment='Customer group name (BMS: tclie_ngrup)',
               existing_nullable=True)
    op.alter_column('customer', 'auto_packaging',
               existing_type=sa.BOOLEAN(),
               comment='Auto packaging flag (BMS: bragg_ximba)',
               existing_nullable=True)
    op.alter_column('customer', 'cash_payment',
               existing_type=sa.BOOLEAN(),
               comment='Cash payment preference (BMS: bcafl)',
               existing_nullable=True)
    op.alter_column('customer', 'financial_status',
               existing_type=sa.VARCHAR(),
               comment='Financial status code (BMS: cstat_dfiac)',
               existing_nullable=True)
    op.alter_column('customer', 'business_start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Business activity start date (BMS: dinse_ianag)',
               existing_nullable=True)
    op.alter_column('customer', 'gender',
               existing_type=sa.VARCHAR(length=1),
               comment='Gender M/F/O (BMS: csess)',
               existing_nullable=True)
    op.alter_column('customer', 'activity_category',
               existing_type=sa.VARCHAR(),
               comment='Activity/industry sector (BMS: ccate_satti)',
               existing_nullable=True)
    op.alter_column('customer', 'customer_category',
               existing_type=sa.VARCHAR(),
               comment='Customer category/classification (BMS: ccate_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Credit limit amount (BMS: asogl_xivas)',
               existing_nullable=True)
    op.alter_column('customer', 'registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Initial registration date (BMS: ianag_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'vat_number',
               existing_type=sa.VARCHAR(length=11),
               comment='Italian VAT number - P.IVA (BMS: cpiva)',
               existing_nullable=True)
    op.alter_column('customer', 'fiscal_code',
               existing_type=sa.VARCHAR(length=16),
               comment='Italian tax code - codice fiscale (BMS: cfisc)',
               existing_nullable=True)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               comment='Last name for individuals (BMS: rcogn)',
               existing_nullable=True)
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               comment='First name for individuals (BMS: rnome)',
               existing_nullable=True)
    op.alter_column('customer', 'business_name',
               existing_type=sa.VARCHAR(),
               comment='Full business/trade name (BMS: traso)',
               existing_nullable=True)
    op.alter_column('customer', 'public_customer_code',
               existing_type=sa.VARCHAR(),
               comment='Public code shown on invoices (BMS: ncocg)',
               existing_nullable=True)
    op.alter_column('customer', 'customer_code',
               existing_type=sa.VARCHAR(),
               comment='Internal customer code (BMS: canag_sclie)',
               existing_nullable=True)
    op.alter_column('customer', 'contact_phone',
               existing_type=sa.VARCHAR(),
               comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('customer', 'contact_email',
               existing_type=sa.VARCHAR(),
               comment='Contact email address',
               existing_nullable=True)
    # ### end Alembic commands ###
